import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/elements/Header'
import Nav from '@/components/elements/Nav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={inter.className}>
        <Header/>
        <Nav/>
        {children}</body>
    </html>
  )
}
