import './globals.css'
import Footer from '@/components/modules/Footer'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>

      <body>
        {children}
        <Footer />
      </body>

    </html>
  )
}
