import Header from '@/components/elements/Header'
import './globals.css'
import Footer from '@/components/modules/Footer'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body>
        <div className="sticky top-0 right-0 left-0 z-[2] w-full ">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
